apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'Prometheus'
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Request Rate'
            query: 'sum(rate(http_server_requests_seconds_count{$$__tags}[5m]))'
      nodeGraph:
        enabled: true
      search:
        hide: false
